<?php

namespace mvbplugins\fslightbox;

if ( ! \defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Loads a local JSON configuration file and validates it against a schema.
 *
 * The file paths must be generated by trusted plugin code and must not be
 * taken directly from request parameters.
 *
 * @param string $config_file Absolute path to the configuration file.
 * @param string $schema_file Absolute path to the schema file.
 *
 * @return array<string, mixed>|\WP_Error Validated configuration or error.
 */
function load_and_validate_json_config( string $config_file, string $schema_file ): array|\WP_Error 
{
	if ( '' === $config_file || ! is_file( $config_file ) ) {
		return new \WP_Error(
			'mvb_config_missing',
			__( 'The configuration file ' . $config_file . ' does not exist.', 'simple-lightbox-fslight' )
		);
	}

	if ( '' === $schema_file || ! is_file( $schema_file ) ) {
		return new \WP_Error(
			'mvb_schema_missing',
			__( 'The configuration schema ' . $schema_file . ' does not exist.', 'simple-lightbox-fslight' )
		);
	}

	if ( ! is_readable( $config_file ) ) {
		return new \WP_Error(
			'mvb_config_not_readable',
			__( 'The configuration file ' . $config_file . ' is not readable.', 'simple-lightbox-fslight' )
		);
	}

	if ( ! is_readable( $schema_file ) ) {
		return new \WP_Error(
			'mvb_schema_not_readable',
			__( 'The configuration schema ' . $schema_file . ' is not readable.', 'simple-lightbox-fslight' )
		);
	}

	$config_json = file_get_contents( $config_file );

	if ( false === $config_json ) {
		return new \WP_Error(
			'mvb_config_read_error',
			__( 'The configuration file ' . $config_file . ' could not be read.', 'simple-lightbox-fslight' )
		);
	}

	$schema_json = file_get_contents( $schema_file );

	if ( false === $schema_json ) {
		return new \WP_Error(
			'mvb_schema_read_error',
			__( 'The configuration schema ' . $schema_file . ' could not be read.', 'simple-lightbox-fslight' )
		);
	}

	try {
		$config = json_decode(
			$config_json,
			true,
			512,
			JSON_THROW_ON_ERROR
		);

		$schema = json_decode(
			$schema_json,
			true,
			512,
			JSON_THROW_ON_ERROR
		);
	} catch ( \JsonException $exception ) {
		return new \WP_Error(
			'mvb_invalid_json',
			\sprintf(
				/* translators: %s: JSON parser error message. */
				__( 'Invalid JSON: %s', 'simple-lightbox-fslight' ),
				$exception->getMessage()
			)
		);
	}

	if ( ! \is_array( $config ) ) {
		return new \WP_Error(
			'mvb_invalid_config_root',
			__(
				'The configuration in file ' . $config_file . ' must contain a JSON object.',
				'simple-lightbox-fslight'
			)
		);
	}

	if ( ! \is_array( $schema ) ) {
		return new \WP_Error(
			'mvb_invalid_schema_root',
			__(
				'The configuration schema ' . $schema_file . ' must contain a JSON object.',
				'simple-lightbox-fslight'
			)
		);
	}

	$validation = rest_validate_value_from_schema(
		$config,
		$schema,
		'plugin configuration'
	);

	if ( is_wp_error( $validation ) ) {
		return $validation;
	}

	return $config;
}